spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;SelectMethod=cursor;
    username: sa
    password: admin
  mvc:
    view:
      prefix : classpath:/templates/
      suffix : .html
    
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath*:com/example/demo/mapper/*.xml
  

server:
    port: 9999
    servlet:
      context-path: /test